### ISSUE TITLE
Question on model evaluation

### ISSUE THREAD

**Issue by VRM1** [adrianjav/heterogeneous_vaes#1]
Thanks for the implementation! I was curious as to why you have both mask and mask_bc under `miscelanea.py -> function def test_mie_ll` as `dataset[:][2]`. Shouldn't the `mask_bc = dataset[:][1]` ? i.e., we need to be applying the mask when encoding and then generate the data. `dataset[:][2]` refers to the variable `nan_mask` (in file datasets.py) which is essentially all ones. It will be great if you can clarify this. 

Thanks

**Comment by adrianjav** [comment]
Hi @VRM1. You are completely right, we should feed the observed mask `dataset[:][1]` to the model, and then use the missing mask to compute the missing imputation error and likelihood.

This is fixed in my [follow-up repository](https://github.com/adrianjav/impartial-vaes/blob/main/heterogeneous/src/miscelanea.py) for another project, but somehow I forgot to update this repository.

Thanks a lot for noticing, I will update it now.
